name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run Prettier
        run: npx prettier . --check
        continue-on-error: true

      - name: Typecheck
        run: npx tsc -b
        continue-on-error: true

      - name: Lint
        run: npx eslint .
        continue-on-error: true
